// frontend/src/lib/components/ProgressBar.svelte
<script lang="ts">
  interface Props {
    progress: number | null
    stage?: string | null
    cancellable?: boolean
    oncancel?: () => void
    class?: string
  }

  let { progress, stage = null, cancellable = false, oncancel, class: className = '' }: Props = $props()
  const stageLabels: Record<string, string> = {
    queued: 'В очереди', uploading: 'Загружаю', downloading: 'Скачиваю', processing: 'Обрабатываю',
  }
  let known = $derived(typeof progress === 'number')
  let label = $derived(`${stage ? stageLabels[stage] ?? stage : 'Работаю'}${known ? ` · ${Math.round(progress as number)}%` : '…'}`)
</script>

<div class={`progress ${className}`.trim()}>
  <div class="progress-head">
    <span class="progress-label">{label}</span>
    {#if cancellable}<button type="button" class="btn ghost sm" onclick={oncancel}>Отмена</button>{/if}
  </div>
  <div class="progress-track">
    <div
      class:indeterminate={!known}
      class="progress-fill"
      style:width={known ? `${Math.max(2, progress as number)}%` : undefined}
    ></div>
  </div>
</div>

// frontend/src/components/ProgressBar.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  progress: number | null
  stage?: string | null
  cancellable?: boolean
}>()

defineEmits<{ cancel: [] }>()

const stageLabels: Record<string, string> = {
  queued: 'В очереди',
  uploading: 'Загружаю',
  downloading: 'Скачиваю',
  processing: 'Обрабатываю',
}

const label = computed(() => {
  const s = props.stage ? stageLabels[props.stage] ?? props.stage : 'Работаю'
  if (typeof props.progress === 'number') return `${s} · ${Math.round(props.progress)}%`
  return `${s}…`
})

const known = computed(() => typeof props.progress === 'number')
</script>

<template>
  <div class="progress">
    <div class="progress-head">
      <span class="progress-label">{{ label }}</span>
      <button v-if="cancellable" type="button" class="btn ghost sm" @click="$emit('cancel')">
        Отмена
      </button>
    </div>
    <div class="progress-track">
      <div
        class="progress-fill"
        :class="{ indeterminate: !known }"
        :style="known ? { width: Math.max(2, progress as number) + '%' } : undefined"
      ></div>
    </div>
  </div>
</template>
