// frontend/src/lib/components/TrimSlider.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'

  interface Props {
    min: number
    max: number
    start: number
    end: number
    step?: number
    gap?: number
    onstartchange?: (value: number) => void
    onendchange?: (value: number) => void
    oninteractionstart?: () => void
    oninteractionend?: () => void
  }

  let {
    min,
    max,
    start,
    end,
    step = 0.1,
    gap = 0.1,
    onstartchange,
    onendchange,
    oninteractionstart,
    oninteractionend,
  }: Props = $props()

  let track: HTMLElement
  let active: 'start' | 'end' | null = null
  const pct = (value: number) => max <= min ? 0 : Math.max(0, Math.min(100, ((value - min) / (max - min)) * 100))
  let startPct = $derived(pct(start))
  let endPct = $derived(pct(end))

  const snap = (value: number) => Math.round(value / step) * step
  const clampStart = (value: number) => Math.max(min, Math.min(snap(value), end - gap))
  const clampEnd = (value: number) => Math.min(max, Math.max(snap(value), start + gap))

  function valueFromClientX(clientX: number): number {
    if (!track) return min
    const rect = track.getBoundingClientRect()
    const ratio = rect.width <= 0 ? 0 : (clientX - rect.left) / rect.width
    return min + Math.max(0, Math.min(1, ratio)) * (max - min)
  }

  function onMove(event: PointerEvent): void {
    if (!active) return
    const value = valueFromClientX(event.clientX)
    if (active === 'start') onstartchange?.(clampStart(value))
    else onendchange?.(clampEnd(value))
  }

  function stopDrag(): void {
    const wasActive = active !== null
    active = null
    window.removeEventListener('pointermove', onMove)
    window.removeEventListener('pointerup', stopDrag)
    window.removeEventListener('pointercancel', stopDrag)
    if (wasActive) oninteractionend?.()
  }

  function startDrag(which: 'start' | 'end', event: PointerEvent): void {
    event.stopPropagation()
    if (!active) oninteractionstart?.()
    active = which
    ;(event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId)
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', stopDrag)
    window.addEventListener('pointercancel', stopDrag)
  }

  function onTrackDown(event: PointerEvent): void {
    if ((event.target as HTMLElement).classList.contains('trim-handle')) return
    const value = valueFromClientX(event.clientX)
    const which = Math.abs(value - start) <= Math.abs(value - end) ? 'start' : 'end'
    startDrag(which, event)
    if (which === 'start') onstartchange?.(clampStart(value))
    else onendchange?.(clampEnd(value))
  }

  function onKey(which: 'start' | 'end', event: KeyboardEvent): void {
    const amount = event.shiftKey ? 1 : step
    let delta = 0
    if (event.key === 'ArrowLeft' || event.key === 'ArrowDown') delta = -amount
    else if (event.key === 'ArrowRight' || event.key === 'ArrowUp') delta = amount
    else return
    event.preventDefault()
    if (which === 'start') onstartchange?.(clampStart(start + delta))
    else onendchange?.(clampEnd(end + delta))
  }

  onDestroy(stopDrag)
</script>

<div class="trim">
  <div bind:this={track} class="trim-track" role="group" aria-label="Диапазон обрезки" onpointerdown={onTrackDown}>
    <div class="trim-fill" style:left={`${startPct}%`} style:width={`${endPct - startPct}%`}></div>
    <div
      class="trim-handle"
      style:left={`${startPct}%`}
      tabindex="0"
      role="slider"
      aria-label="Начало обрезки"
      aria-valuemin={min}
      aria-valuemax={max}
      aria-valuenow={start}
      onpointerdown={(event) => startDrag('start', event)}
      onkeydown={(event) => onKey('start', event)}
    ></div>
    <div
      class="trim-handle"
      style:left={`${endPct}%`}
      tabindex="0"
      role="slider"
      aria-label="Конец обрезки"
      aria-valuemin={min}
      aria-valuemax={max}
      aria-valuenow={end}
      onpointerdown={(event) => startDrag('end', event)}
      onkeydown={(event) => onKey('end', event)}
    ></div>
  </div>
</div>

// frontend/src/components/TrimSlider.vue
<script setup lang="ts">
import { computed, onUnmounted, ref } from 'vue'

const props = withDefaults(
  defineProps<{
    min: number
    max: number
    start: number
    end: number
    step?: number
  }>(),
  { step: 0.1 },
)

const emit = defineEmits<{
  'update:start': [number]
  'update:end': [number]
}>()

const GAP = 0.1
const track = ref<HTMLElement | null>(null)
let active: 'start' | 'end' | null = null

function pct(v: number): number {
  const range = props.max - props.min
  if (range <= 0) return 0
  return Math.max(0, Math.min(100, ((v - props.min) / range) * 100))
}

const startPct = computed(() => pct(props.start))
const endPct = computed(() => pct(props.end))

function snap(v: number): number {
  const s = props.step
  return Math.round(v / s) * s
}

function clampStart(v: number): number {
  return Math.max(props.min, Math.min(snap(v), props.end - GAP))
}

function clampEnd(v: number): number {
  return Math.min(props.max, Math.max(snap(v), props.start + GAP))
}

function valueFromClientX(x: number): number {
  const el = track.value
  if (!el) return props.min
  const rect = el.getBoundingClientRect()
  const t = rect.width <= 0 ? 0 : (x - rect.left) / rect.width
  return props.min + Math.max(0, Math.min(1, t)) * (props.max - props.min)
}

function onMove(e: PointerEvent): void {
  if (!active) return
  const v = valueFromClientX(e.clientX)
  if (active === 'start') emit('update:start', clampStart(v))
  else emit('update:end', clampEnd(v))
}

function onUp(): void {
  stopDrag()
}

function stopDrag(): void {
  active = null
  window.removeEventListener('pointermove', onMove)
  window.removeEventListener('pointerup', onUp)
}

onUnmounted(stopDrag)

function startDrag(which: 'start' | 'end', e: PointerEvent): void {
  active = which
  ;(e.target as HTMLElement).setPointerCapture?.(e.pointerId)
  window.addEventListener('pointermove', onMove)
  window.addEventListener('pointerup', onUp)
}

// Clicking the bare track jumps the nearest handle there, then drags it.
function onTrackDown(e: PointerEvent): void {
  if ((e.target as HTMLElement).classList.contains('trim-handle')) return
  const v = valueFromClientX(e.clientX)
  const which = Math.abs(v - props.start) <= Math.abs(v - props.end) ? 'start' : 'end'
  if (which === 'start') emit('update:start', clampStart(v))
  else emit('update:end', clampEnd(v))
  startDrag(which, e)
}

function onKey(which: 'start' | 'end', e: KeyboardEvent): void {
  const big = e.shiftKey ? 1 : props.step
  let d = 0
  if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') d = -big
  else if (e.key === 'ArrowRight' || e.key === 'ArrowUp') d = big
  else return
  e.preventDefault()
  if (which === 'start') emit('update:start', clampStart(props.start + d))
  else emit('update:end', clampEnd(props.end + d))
}
</script>

<template>
  <div class="trim">
    <div ref="track" class="trim-track" @pointerdown="onTrackDown">
      <div class="trim-fill" :style="{ left: startPct + '%', width: endPct - startPct + '%' }"></div>
      <div
        class="trim-handle"
        :style="{ left: startPct + '%' }"
        tabindex="0"
        role="slider"
        aria-label="Начало обрезки"
        :aria-valuemin="min"
        :aria-valuemax="max"
        :aria-valuenow="start"
        @pointerdown="startDrag('start', $event)"
        @keydown="onKey('start', $event)"
      ></div>
      <div
        class="trim-handle"
        :style="{ left: endPct + '%' }"
        tabindex="0"
        role="slider"
        aria-label="Конец обрезки"
        :aria-valuemin="min"
        :aria-valuemax="max"
        :aria-valuenow="end"
        @pointerdown="startDrag('end', $event)"
        @keydown="onKey('end', $event)"
      ></div>
    </div>
  </div>
</template>
