// frontend/src/lib/components/UrlImport.svelte
<script lang="ts">
  import ProgressBar from './ProgressBar.svelte'
  import { cancelImport, doImport, doUpload, state as appState } from '$lib/state/store.svelte.js'

  let picker: HTMLInputElement
  let dragover = $state(false)

  function onPick(event: Event): void {
    const input = event.currentTarget as HTMLInputElement
    const file = input.files?.[0]
    if (file) void doUpload(file)
    input.value = ''
  }

  function onDrop(event: DragEvent): void {
    event.preventDefault()
    dragover = false
    const file = event.dataTransfer?.files?.[0]
    if (file) void doUpload(file)
  }
</script>

<div
  class:dragover
  class="card import"
  role="region"
  aria-label="Импорт видео"
  ondragover={(event) => { event.preventDefault(); dragover = true }}
  ondragleave={(event) => { event.preventDefault(); dragover = false }}
  ondrop={onDrop}
>
  <div class="row">
    <input
      bind:value={appState.url}
      class="url-input"
      type="url"
      placeholder="https://vkvideo.ru/video-220018529_456248395"
      disabled={appState.importing}
      onkeydown={(event) => { if (event.key === 'Enter') void doImport() }}
    />
    <button class="btn primary" disabled={appState.importing || !appState.url.trim()} onclick={() => void doImport()}>
      {appState.importing ? 'Загрузка…' : 'Импорт'}
    </button>
  </div>
  <div class="range-row">
    <label>с <input bind:value={appState.importStart} class="time-input" placeholder="0:30" disabled={appState.importing} /></label>
    <label>по <input bind:value={appState.importEnd} class="time-input" placeholder="2:00" disabled={appState.importing} /></label>
    <span class="hint">диапазон импорта (мм:сс). Пусто = всё видео, для длинных роликов укажи отрезок</span>
  </div>
  <div class="import-or"><span>или</span></div>
  <button type="button" class="dropzone" disabled={appState.importing} onclick={() => picker?.click()}>
    <input bind:this={picker} type="file" accept="video/*" class="hidden-file" onchange={onPick} />
    <span class="dropzone-icon">📁</span>
    <span>Перетащи видеофайл сюда или нажми, чтобы выбрать</span>
  </button>
  {#if appState.importing}
    <ProgressBar
      class="import-progress"
      progress={appState.importProgress}
      stage={appState.importStage}
      cancellable={appState.importStage !== 'uploading'}
      oncancel={() => void cancelImport()}
    />
  {/if}
  {#if appState.importError}<p class="error">Ошибка: {appState.importError}</p>{/if}
</div>

// frontend/src/components/UrlImport.vue
<script setup lang="ts">
import { ref } from 'vue'
import { state, doImport, doUpload, cancelImport } from '../store'
import ProgressBar from './ProgressBar.vue'

const picker = ref<HTMLInputElement | null>(null)
const dragover = ref(false)

function onPick(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (file) void doUpload(file)
  ;(e.target as HTMLInputElement).value = ''
}

function onDrop(e: DragEvent) {
  dragover.value = false
  const file = e.dataTransfer?.files?.[0]
  if (file) void doUpload(file)
}
</script>

<template>
  <div
    class="card import"
    :class="{ dragover }"
    @dragover.prevent="dragover = true"
    @dragleave.prevent="dragover = false"
    @drop.prevent="onDrop"
  >
    <div class="row">
      <input
        v-model="state.url"
        class="url-input"
        type="url"
        placeholder="https://vkvideo.ru/video-220018529_456248395"
        :disabled="state.importing"
        @keyup.enter="doImport"
      />
      <button
        class="btn primary"
        :disabled="state.importing || !state.url.trim()"
        @click="doImport"
      >
        {{ state.importing ? 'Загрузка…' : 'Импорт' }}
      </button>
    </div>
    <div class="range-row">
      <label>с <input v-model="state.importStart" class="time-input" placeholder="0:30" :disabled="state.importing" /></label>
      <label>по <input v-model="state.importEnd" class="time-input" placeholder="2:00" :disabled="state.importing" /></label>
      <span class="hint">диапазон импорта (мм:сс). Пусто = всё видео, для длинных роликов укажи отрезок</span>
    </div>

    <div class="import-or"><span>или</span></div>

    <button type="button" class="dropzone" :disabled="state.importing" @click="picker?.click()">
      <input ref="picker" type="file" accept="video/*" class="hidden-file" @change="onPick" />
      <span class="dropzone-icon">📁</span>
      <span>Перетащи видеофайл сюда или нажми, чтобы выбрать</span>
    </button>

    <ProgressBar
      v-if="state.importing"
      class="import-progress"
      :progress="state.importProgress"
      :stage="state.importStage"
      :cancellable="state.importStage !== 'uploading'"
      @cancel="cancelImport"
    />
    <p v-if="state.importError" class="error">Ошибка: {{ state.importError }}</p>
  </div>
</template>
