// frontend/src/components/RectOverlay.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { state } from '../store'

interface Rect {
  x: number
  y: number
  w: number
  h: number
}

const props = withDefaults(
  defineProps<{
    rect: Rect
    color?: string
    // crop dims the area outside; mask fills the rectangle instead.
    mode?: 'crop' | 'mask'
  }>(),
  { color: 'var(--accent)', mode: 'crop' },
)

const emit = defineEmits<{ 'update:rect': [Rect] }>()

const root = ref<HTMLElement | null>(null)
const MIN = 16

type Mode = 'move' | 'nw' | 'ne' | 'sw' | 'se'
let dragMode: Mode | null = null
let startX = 0
let startY = 0
let orig: Rect = { x: 0, y: 0, w: 0, h: 0 }

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(v, hi))
}

function dims() {
  return { W: state.video?.width || 1, H: state.video?.height || 1 }
}

const rectStyle = computed(() => {
  const { W, H } = dims()
  const c = props.rect
  return {
    left: `${(c.x / W) * 100}%`,
    top: `${(c.y / H) * 100}%`,
    width: `${(c.w / W) * 100}%`,
    height: `${(c.h / H) * 100}%`,
    borderColor: props.color,
    boxShadow: props.mode === 'crop' ? '0 0 0 9999px rgba(0, 0, 0, 0.45)' : 'none',
    background: props.mode === 'mask' ? 'rgba(255, 80, 80, 0.32)' : 'transparent',
  }
})

function toSrc(dxPx: number, dyPx: number) {
  const r = root.value!.getBoundingClientRect()
  const { W, H } = dims()
  return { dx: (dxPx / r.width) * W, dy: (dyPx / r.height) * H }
}

function begin(m: Mode, e: PointerEvent) {
  dragMode = m
  startX = e.clientX
  startY = e.clientY
  orig = { ...props.rect }
  ;(e.target as HTMLElement).setPointerCapture?.(e.pointerId)
  window.addEventListener('pointermove', onMove)
  window.addEventListener('pointerup', onUp)
  e.preventDefault()
  e.stopPropagation()
}

function onMove(e: PointerEvent) {
  if (!dragMode) return
  const { dx, dy } = toSrc(e.clientX - startX, e.clientY - startY)
  const { W, H } = dims()
  if (dragMode === 'move') {
    const x = clamp(orig.x + dx, 0, W - orig.w)
    const y = clamp(orig.y + dy, 0, H - orig.h)
    emit('update:rect', { x: Math.round(x), y: Math.round(y), w: orig.w, h: orig.h })
    return
  }
  let x1 = orig.x
  let y1 = orig.y
  let x2 = orig.x + orig.w
  let y2 = orig.y + orig.h
  if (dragMode.includes('w')) x1 = clamp(orig.x + dx, 0, x2 - MIN)
  if (dragMode.includes('e')) x2 = clamp(orig.x + orig.w + dx, x1 + MIN, W)
  if (dragMode.includes('n')) y1 = clamp(orig.y + dy, 0, y2 - MIN)
  if (dragMode.includes('s')) y2 = clamp(orig.y + orig.h + dy, y1 + MIN, H)
  emit('update:rect', {
    x: Math.round(x1),
    y: Math.round(y1),
    w: Math.round(x2 - x1),
    h: Math.round(y2 - y1),
  })
}

function onUp() {
  dragMode = null
  window.removeEventListener('pointermove', onMove)
  window.removeEventListener('pointerup', onUp)
}
</script>

<template>
  <div ref="root" class="crop-overlay">
    <div class="crop-rect" :style="rectStyle" @pointerdown="begin('move', $event)">
      <span class="crop-handle nw" :style="{ borderColor: color }" @pointerdown="begin('nw', $event)"></span>
      <span class="crop-handle ne" :style="{ borderColor: color }" @pointerdown="begin('ne', $event)"></span>
      <span class="crop-handle sw" :style="{ borderColor: color }" @pointerdown="begin('sw', $event)"></span>
      <span class="crop-handle se" :style="{ borderColor: color }" @pointerdown="begin('se', $event)"></span>
    </div>
  </div>
</template>

// frontend/src/lib/components/RectOverlay.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'
  import { state } from '$lib/state/store.svelte.js'

  interface OverlayRect { x: number; y: number; w: number; h: number }
  interface Props {
    rect: OverlayRect
    color?: string
    mode?: 'crop' | 'mask'
    onrectchange?: (rect: OverlayRect) => void
    oninteractionstart?: () => void
    oninteractionend?: () => void
  }

  let {
    rect,
    color = 'var(--accent)',
    mode = 'crop',
    onrectchange,
    oninteractionstart,
    oninteractionend,
  }: Props = $props()
  let root: HTMLElement
  const MIN = 16
  type DragMode = 'move' | 'nw' | 'ne' | 'sw' | 'se'
  let dragMode: DragMode | null = null
  let startX = 0
  let startY = 0
  let original: OverlayRect = { x: 0, y: 0, w: 0, h: 0 }

  const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(value, max))
  const dims = () => ({ width: state.video?.width || 1, height: state.video?.height || 1 })
  function normalize(value: OverlayRect): OverlayRect {
    const { width, height } = dims()
    const minWidth = Math.min(MIN, width)
    const minHeight = Math.min(MIN, height)
    const finite = (input: number, fallback: number) => Number.isFinite(input) ? input : fallback
    const w = clamp(Math.round(finite(value.w, minWidth)), minWidth, width)
    const h = clamp(Math.round(finite(value.h, minHeight)), minHeight, height)
    return {
      x: clamp(Math.round(finite(value.x, 0)), 0, width - w),
      y: clamp(Math.round(finite(value.y, 0)), 0, height - h),
      w,
      h,
    }
  }
  let normalized = $derived(normalize(rect))
  let rectStyle = $derived([
    `left:${normalized.x / dims().width * 100}%`,
    `top:${normalized.y / dims().height * 100}%`,
    `width:${normalized.w / dims().width * 100}%`,
    `height:${normalized.h / dims().height * 100}%`,
    `border-color:${color}`,
    `box-shadow:${mode === 'crop' ? '0 0 0 9999px rgba(0, 0, 0, 0.45)' : 'none'}`,
    `background:${mode === 'mask' ? 'rgba(255, 80, 80, 0.32)' : 'transparent'}`,
  ].join(';'))

  function sourceDelta(dx: number, dy: number): { dx: number; dy: number } | null {
    if (!root) return null
    const bounds = root.getBoundingClientRect()
    if (bounds.width <= 0 || bounds.height <= 0) return null
    const { width, height } = dims()
    return { dx: dx * width / bounds.width, dy: dy * height / bounds.height }
  }
  function begin(nextMode: DragMode, event: PointerEvent): void {
    dragMode = nextMode
    startX = event.clientX
    startY = event.clientY
    original = normalize(rect)
    oninteractionstart?.()
    ;(event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId)
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', stopDrag)
    event.preventDefault()
    event.stopPropagation()
  }
  function onMove(event: PointerEvent): void {
    if (!dragMode) return
    const delta = sourceDelta(event.clientX - startX, event.clientY - startY)
    if (!delta) return stopDrag()
    const { width, height } = dims()
    const minWidth = Math.min(MIN, width)
    const minHeight = Math.min(MIN, height)
    if (dragMode === 'move') {
      onrectchange?.(normalize({ ...original, x: original.x + delta.dx, y: original.y + delta.dy }))
      return
    }
    let x1 = original.x
    let y1 = original.y
    let x2 = original.x + original.w
    let y2 = original.y + original.h
    if (dragMode.includes('w')) x1 = clamp(original.x + delta.dx, 0, x2 - minWidth)
    if (dragMode.includes('e')) x2 = clamp(original.x + original.w + delta.dx, x1 + minWidth, width)
    if (dragMode.includes('n')) y1 = clamp(original.y + delta.dy, 0, y2 - minHeight)
    if (dragMode.includes('s')) y2 = clamp(original.y + original.h + delta.dy, y1 + minHeight, height)
    onrectchange?.(normalize({ x: x1, y: y1, w: x2 - x1, h: y2 - y1 }))
  }
  function stopDrag(): void {
    const wasDragging = dragMode !== null
    dragMode = null
    window.removeEventListener('pointermove', onMove)
    window.removeEventListener('pointerup', stopDrag)
    if (wasDragging) oninteractionend?.()
  }
  onDestroy(stopDrag)
</script>

<div bind:this={root} class="crop-overlay">
  <div class="crop-rect" style={rectStyle} role="group" aria-label="Редактируемая область кадра" onpointerdown={(event) => begin('move', event)}>
    {#each ['nw', 'ne', 'sw', 'se'] as handle (handle)}
      <span
        class={`crop-handle ${handle}`}
        style:border-color={color}
        role="button"
        tabindex="0"
        aria-label={`Изменить размер области: ${handle}`}
        onpointerdown={(event) => begin(handle as DragMode, event)}
        onkeydown={(event) => { if (event.key === 'Enter' || event.key === ' ') event.preventDefault() }}
      ></span>
    {/each}
  </div>
</div>
